### ISSUE TITLE
cfg files in local ~/.teal directories are unknowingly being picked up

### ISSUE THREAD

**Issue by mackjenn** [spacetelescope/drizzlepac#111]
Numerous users have been stumbling over this issue...

When running drizzlepac tools in a python session, sometimes the software crashes due to parameters specified in a local cfg file being picked up unknowingly.  

For example, when the astrodrizzle.cfg file has a parameter 'final_refimage' specified, running the command astrodrizzle.AstroDrizzle('*flc.fits') crashes, complaining it cannot find the reference image.  To get around this, we tell users to do this:
from stsci.tools import teal
teal.unlearn('astrodrizzle') 

But there are often other cfg files the user isn't aware of... for example, if you drizzle with sky matching, you also have to remove skymatch.cfg. If you run tweakreg, you also have to remove imagefindpars.cfg and refimagefindpars.cfg.  

This means unlearning a lot of stuff. Alternately, we could tell people to simply do:
rm ~/.teal/*cfg

I'm wondering if we can modify the software to give a warning if local *cfg files are present and being picked up? Or else to have the software just ignore those files if the session is being run in any way other than via the teal GUI?

**Comment by mcara** [comment]
I have encountered the same issue but I always thought that this was by design. And I agree with you that this is somewhat confusing because I would expect a function to load "default" values. The thing, unfortunately, is that tweakreg & astrodrizzle was designed to load "defaults" from a configuration file. The question for me is why was it designed this way @stsci-hack ? It could be that this is how it was conceived to work in the pipeline. Therefore we need to understand if a change in how drizzlepac loads defaults (or not specified by user parameters) will have an effect on existing pipelines.

@stsci-hack is the expert on this [<-- assigning this issue]

**Comment by mcara** [comment]
I have implemented a solution in https://github.com/spacetelescope/drizzlepac/pull/112 that will allow telling `drizzlepac` (both `tweakreg` and `astrodrizzle`) to load "designed" defaults instead of what is found in `~/.teal/*.cfg`. Essentially you will have to call, `AstroDrizzle` as:

```python
astrodrizzle.AstroDrizzle('*flc.fits', configobj='defaults')
```

**Comment by mcara** [comment]
Release 2.1.22 should contain this fix.

**Comment by mackjenn** [comment]
This is helpful but doesn't completely solve the problem.  
It assumes users will find (and read) documentation related to the change in order to be aware of the new feature.

If the user types:
astrodrizzle.AstroDrizzle('*flc.fits') 
the software will still crash if there are local cfg files lying around with conflicting parameters.

**Comment by mcara** [comment]
True, but I think it is reasonable to assume that users read documentation. I cannot write software that reads minds [at least, not yet].

With regard to changing default for `configobj` from `None` to `'defaults'` - that may be a big problem: first, the pipeline may be relying on specific behavior of drizzlepac, and second, there may be users who wrote their own pipelines relying on the old behavior of the drizzlepac.

So, while I did not change default behavior for the drizzlepac, I gave you tools to accomplish what you need by setting `configobj='defaults'`.

@stsci-hack What is your opinion on changing defaults for drizzlepac?

**Comment by mcara** [comment]
Another possible consequence of changing defaults would be to rewrite parts of the drizzlepac manual: http://documents.stsci.edu/hst/HST_overview/documents/DrizzlePac/ch56.html for those few users who do read documentation 😄

**Comment by stsci-hack** [comment]
It turns out that the pipeline actually calls 'drizzlepac.astrodrizzle' with configobj='defaults' itself.  Changing the defaults for the end-user would then cause them to simply run the code like the pipeline by default, which may still not be what they expect if projects like the HLA have written their own code to use astrodrizzle.  Still, this may be the best option given the more complicated nature of config file compared to the simpler IRAF par files and how IRAF treated them with their defaults.   

This change in default behavior could also be something that we highlight in our astroconda release 'Incompatability' or 'Release Notes' page (whichever seems more appropriate or perhaps both) so that anyone looking to get this update would be alerted when they download this new version without having to read separate docs (which should eventually be updated as well...).

**Comment by mcara** [comment]
> It turns out that the pipeline actually calls 'drizzlepac.astrodrizzle' with configobj='defaults' itself. 

Well, that is a problem... because in the old code `'defaults'` was equivalent to `None`. That is, by changing what code does when `configobj='defaults'` we have changed how pipeline loads defaults!!! Will this cause problems?

With regard to documenting the changes - is it worth it if user do not read documentation even when they find it?

**Comment by mcara** [comment]
OK, I'll make a new PR and a new release once we get more changes. How do you want the default for configobj to be ?

**OPTION 1:** Change the default value for `configobj` from `None` to `'defaults'` - so that when run from command line, drizzlepac loads *"documented defaults"* instead of , e.g., values from `~/.teal/astrodrizzle.cfg`. That is, `configobj=None` means load from `.teal/` and [default action] `configobj='defaults'` means load "true" defaults?

**OPTION 2:** Keep default value to `None` but make drizzlepac to load "real defaults" (the documented ones). When `configobj='defaults'` - load defaults from, e.g., `~/.teal/astrodrizzle.cfg`. That is, [default action] `configobj=None` means load "true" defaults and `configobj='defaults'` means load from `.teal/`?

**Comment by mcara** [comment]
I implemented Option 2 above in https://github.com/spacetelescope/drizzlepac/pull/115. Now code should do what @mackjenn wants.

**Comment by mcara** [comment]
Fix should be available in the release 2.2.0 starting tomorrow.
